# Generated by Django 4.1.4 on 2023-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendoremployee_alter_customerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='business email address'),
        ),
    ]
