# Generated by Django 4.1.4 on 2023-02-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendorprofile_business_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
