# Generated by Django 4.1.4 on 2023-09-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendorprofile_close_hour_vendorprofile_open_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
