# Generated by Django 4.1.4 on 2023-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orderitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='device token'),
        ),
    ]
