# Generated by Django 4.1.4 on 2023-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
