# Generated by Django 4.1.4 on 2023-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorridertransactionhistory',
            name='deposit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorridertransactionhistory',
            name='title',
            field=models.CharField(blank=True, choices=[('PAYOUT', 'payout'), ('INCOME', 'income'), ('WEB TOP UP', 'Web Top Up')], max_length=100, null=True),
        ),
    ]
