# Generated by Django 4.1.4 on 2023-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_vendoremployeeprofile_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=10315),
        ),
    ]
