# Generated by Django 4.1.4 on 2023-03-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_num',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=3941),
        ),
    ]
