# Generated by Django 4.1.4 on 2023-03-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='borrow_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='borrowed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=75110),
        ),
    ]
