# Generated by Django 4.1.4 on 2023-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_riderprofile_borrow_limit_riderprofile_borrowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=7710),
        ),
    ]
