# Generated by Django 4.1.4 on 2023-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='no_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
