# Generated by Django 4.1.4 on 2023-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_vendorprofile_no_of_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='average_star_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
