# Generated by Django 4.1.4 on 2023-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_vendorprofile_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rider_in_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
