# Generated by Django 4.1.4 on 2023-03-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_riderprofile_rider_in_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
