# Generated by Django 4.1.4 on 2023-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_riderprofile_amount_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
