# Generated by Django 4.1.4 on 2023-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_vendorprofile_amount_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer/profile_pictures/%Y/%m/%d'),
        ),
    ]
