# Generated by Django 4.1.4 on 2023-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_customerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyphone',
            name='otp',
            field=models.CharField(max_length=64),
        ),
    ]
