# Generated by Django 4.1.4 on 2023-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_verifyphone_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='button_text',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
