# Generated by Django 4.1.4 on 2023-04-18 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_webhookspaymentmessage_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_num',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
