# Generated by Django 4.1.4 on 2023-04-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_number')},
        ),
    ]
