# Generated by Django 4.1.4 on 2023-04-18 14:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_bankaccount_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('summary', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(blank=True, default=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('quantity', models.CharField(choices=[('PER_WRAP', 'Per Wrap'), ('PER_SPOON', 'Per Spoon'), ('PER_PLATE', 'Per Plate')], max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor/menu_item/%Y/%m/%d')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.menucategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_menu_items', to='users.vendor')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PICKUP', 'pickup'), ('DELIVERY', 'delivery')], default='DELIVERY', max_length=20)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_period', models.CharField(choices=[('NOW', 'now'), ('LATER', 'later')], default='NOW', max_length=50)),
                ('later_time', models.DateTimeField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('payment_method', models.CharField(blank=True, choices=[('WEB', 'web'), ('WALLET', 'wallet'), ('WEB_WALLET', 'web wallet')], max_length=20, null=True)),
                ('third_party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('delivery_fee', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('delivered_time', models.TimeField(blank=True, null=True)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CANCELLED', 'Cancelled'), ('ON_DELIVERY', 'On Delivery'), ('DELIVERED', 'Delivered'), ('IN_PROGRESS', 'In Progress')], default='REQUESTED', max_length=50)),
                ('total', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='users.customer')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_orders', to='users.rider')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.JSONField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.menuitem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.order')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('max_items', models.IntegerField(default=0)),
                ('items', models.JSONField(default=list)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='users.menuitem')),
            ],
            options={
                'unique_together': {('item', 'name')},
            },
        ),
    ]
