# Generated by Django 4.1.4 on 2023-04-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_menucategory_menuitem_order_orderitem_menusubitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRiderTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('PAYOUT', 'payout'), ('INCOME', 'income')], max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, default='', help_text='reference', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('transaction_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PROCESSING', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
