# Generated by Django 4.1.4 on 2023-06-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_vendorridertransactionhistory_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorridertransactionhistory',
            name='payment_method',
            field=models.CharField(blank=True, default='Bank Account', max_length=100, null=True),
        ),
    ]
