# Generated by Django 4.1.4 on 2023-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_location_user_location_lat_user_location_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
