# Generated by Django 4.1.4 on 2023-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_user_location_lat_alter_user_location_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('CANCELLED', 'Cancelled'), ('ON_DELIVERY', 'On Delivery'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('IN_PROGRESS', 'In Progress')], default='REQUESTED', max_length=50),
        ),
    ]
