# Generated by Django 4.1.4 on 2023-08-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoremployeepair',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='users.vendoremployee'),
        ),
    ]
