# Generated by Django 4.1.4 on 2023-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_vendoremployeepair_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoremployeeprofile',
            name='App_Access',
        ),
        migrations.AddField(
            model_name='vendoremployeeprofile',
            name='food_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoremployeeprofile',
            name='price_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoremployeeprofile',
            name='wallet_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
