# Generated by Django 4.1.4 on 2023-08-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
