# Generated by Django 4.1.4 on 2023-08-29 10:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PICKUP', 'pickup'), ('DELIVERY', 'delivery')], default='DELIVERY', max_length=20)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_period', models.CharField(choices=[('NOW', 'now'), ('LATER', 'later')], default='NOW', max_length=50)),
                ('later_time', models.DateTimeField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('payment_method', models.CharField(blank=True, choices=[('WEB', 'web'), ('WALLET', 'wallet'), ('WEB_WALLET', 'web wallet')], max_length=20, null=True)),
                ('third_party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_delivery_fee', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='users.customer')),
            ],
        ),
        migrations.RenameField(
            model_name='menusubitem',
            old_name='max_items',
            new_name='max_num_choices',
        ),
        migrations.RemoveField(
            model_name='menusubitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='menusubitem',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.FloatField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('delivered_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CANCELLED', 'Cancelled'), ('ON_DELIVERY', 'On Delivery'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('IN_PROGRESS', 'In Progress')], default='REQUESTED', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.customerorder')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_orders', to='users.rider')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='users.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_items', to='users.customerorder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order_items', to='users.vendororder'),
        ),
        migrations.AlterField(
            model_name='vendorridertransactionhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vendororder'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
