# Generated by Django 4.1.4 on 2023-08-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_customerorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='users.menuitem'),
        ),
    ]
