# Generated by Django 4.1.4 on 2023-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_orderitem_item_alter_vendororder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
