# Generated by Django 4.1.4 on 2023-09-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_customerorder_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='paid',
            new_name='is_paid',
        ),
    ]
