# Generated by Django 4.1.4 on 2023-09-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_rename_paid_customerorder_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='users.customerorder'),
        ),
    ]
