# Generated by Django 4.1.4 on 2023-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('FOOD PURCHASE', 'Food Purchase'), ('REFUND', 'Refund'), ('WEB TOP UP', 'Web Top Up')], max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, default='', help_text='reference', max_length=100, null=True)),
                ('delivery_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('restaurant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=100)),
                ('checkout_url', models.URLField(blank=True, help_text='checkout url for deposits', null=True)),
            ],
        ),
    ]
