# Generated by Django 4.1.4 on 2023-03-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_otp'),
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('FOOD_PURCHASE', 'Food Purchase'), ('REFUND', 'Refund'), ('WEB TOP UP', 'Web Top Up')], max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('delivery_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('restaurant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
