# Generated by Django 4.1.4 on 2023-09-19 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdeliveryaddress',
            name='number',
        ),
        migrations.AddField(
            model_name='customerdeliveryaddress',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='customerdeliveryaddress',
            name='location_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customerdeliveryaddress',
            name='location_long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
