# Generated by Django 4.1.4 on 2023-03-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_otp'),
        ('customerapp', '0002_customertransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransactionhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='users.customer'),
        ),
    ]
