# Generated by Django 4.1.4 on 2023-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_alter_customertransactionhistory_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransactionhistory',
            name='title',
            field=models.CharField(blank=True, choices=[('FOOD PURCHASE', 'Food Purchase'), ('REFUND', 'Refund'), ('WEB TOP UP', 'Web Top Up')], max_length=100, null=True),
        ),
    ]
