# Generated by Django 4.1.4 on 2023-03-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_otp'),
        ('customerapp', '0004_alter_customertransactionhistory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeliveryaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='users.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customerdeliveryaddress',
            unique_together={('customer', 'label')},
        ),
    ]
