# Generated by Django 4.1.4 on 2023-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_customerdeliveryaddress_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransactionhistory',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='customertransactionhistory',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransactionhistory',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='customertransactionhistory',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='reference', max_length=100, null=True),
        ),
    ]
