# Generated by Django 4.1.4 on 2023-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_remove_customertransactionhistory_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransactionhistory',
            name='payment_method',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
