# Generated by Django 4.1.4 on 2023-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_customertransactionhistory_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransactionhistory',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='checkout url for deposits', null=True),
        ),
    ]
