# Generated by Django 4.1.4 on 2023-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_alter_customertransactionhistory_checkout_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdeliveryaddress',
            name='landmark',
        ),
    ]
