# Generated by Django 4.1.4 on 2023-02-11 11:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_reviews_review'),
        ('vendorapp', '0003_rename_user_menucategory_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PICKUP', 'pickup'), ('DELIVERY', 'delivery')], max_length=20)),
                ('delivery_address', models.TextField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('payment_method', models.CharField(choices=[('WEB', 'web'), ('WALLET', 'wallet')], max_length=20, null=True)),
                ('third_party_name', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(null=True)),
                ('delivery_fee', models.FloatField(null=True)),
                ('vat', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.JSONField()),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='vendorapp.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendorapp.order')),
            ],
        ),
    ]
