# Generated by Django 4.1.4 on 2023-02-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_reviews_review'),
        ('vendorapp', '0005_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order', to='users.vendor'),
        ),
    ]
