# Generated by Django 4.1.4 on 2023-03-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_otp'),
        ('vendorapp', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_period',
            field=models.CharField(choices=[('NOW', 'now'), ('LATER', 'later')], default='NOW', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='later_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_menu_items', to='users.vendor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WEB', 'web'), ('WALLET', 'wallet'), ('WEB_WALLET', 'web wallet')], max_length=20, null=True),
        ),
    ]
