# Generated by Django 4.1.4 on 2023-03-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_riderprofile_rider_in_delivery'),
        ('vendorapp', '0009_order_delivery_period_order_later_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_order', to='users.rider'),
        ),
    ]
