# Generated by Django 4.1.4 on 2023-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0010_order_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
    ]
