# Generated by Django 4.1.4 on 2023-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0012_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.TimeField(null=True),
        ),
    ]
