# Generated by Django 4.1.4 on 2023-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0016_alter_order_delivered_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='availability',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
