# Generated by Django 4.1.4 on 2023-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0018_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='vendor',
        ),
        migrations.AlterUniqueTogether(
            name='menusubitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menusubitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuSubItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
