# Generated by Django 4.1.4 on 2023-03-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_riderprofile_rider_in_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLoan',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('loan_date', models.DateField(null=True)),
                ('comment', models.CharField(blank=True, max_length=64, null=True)),
                ('repayment_end_date', models.DateField(null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('DECLINE', 'Decline')], default='PENDING', max_length=64, null=True)),
                ('purpose', models.CharField(blank=True, max_length=64, null=True)),
                ('repayment_plan', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIWEEKLY', 'BiWeekly')], max_length=64, null=True)),
                ('payment_missing', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderLoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_before_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_after_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payments', to='users.rider')),
                ('rider_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='riderapp.riderloan')),
            ],
        ),
    ]
