# Generated by Django 4.1.4 on 2023-09-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riderapp', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderwallethistory',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_transactions', to='users.rider'),
        ),
        migrations.AddField(
            model_name='riderloanpayment',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payments', to='users.rider'),
        ),
        migrations.AddField(
            model_name='riderloanpayment',
            name='rider_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='riderapp.riderloan'),
        ),
        migrations.AddField(
            model_name='riderloan',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.rider'),
        ),
    ]
