# Generated by Django 4.1.4 on 2023-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderapp', '0002_alter_riderloan_loan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderloanpayment',
            name='source',
        ),
        migrations.AddField(
            model_name='riderloanpayment',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('WALLET', 'Wallet'), ('DEPOSIT', 'Deposit')], max_length=64, null=True),
        ),
    ]
