# Generated by Django 4.1.4 on 2023-03-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderapp', '0004_riderloan_repayment_plan_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderloanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
