# Generated by Django 4.1.4 on 2023-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderapp', '0005_riderloanpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderloanpayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
