# Generated by Django 4.1.4 on 2023-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderapp', '0006_alter_riderloanpayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderloanpayment',
            name='repayment_plan',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='riderloanpayment',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'paid'), ('PENDING', 'pending')], default='PENDING', max_length=64, null=True),
        ),
    ]
