# Generated by Django 4.1.4 on 2023-03-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_riderprofile_amount_earned'),
        ('riderapp', '0007_riderloanpayment_repayment_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderWalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, choices=[('PAYOUT', 'Payout'), ('DAILY_INCOME', 'Daily Income')], max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_transactions', to='users.rider')),
            ],
        ),
    ]
